name: example_pattern
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # infrastructure
  bloc_concurrency: ^0.2.0
  easy_localization: ^3.0.1
  flutter_bloc: ^8.0.1
  freezed: ^2.1.1
  freezed_annotation: ^2.0.0
  get_it: ^7.2.0
  hive: ^2.2.3
  internet_connection_checker: ^1.0.0+1

  # ui
  shimmer: ^2.0.0
  cached_network_image: ^3.2.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg